CREATE TABLE "MIS500"."H131"
(
    dupersid integer,
    panel integer,
    year integer,
    empst31h integer,
    empst42h integer,
    empst53h integer,
    slfcm31h integer,
    slfcm42h integer,
    slfcm53h integer,
    nmemp31h integer,
    nmemp42h integer,
    nmemp53h integer,
    more31h integer,
    more42h integer,
    more53h integer,
    indct31h integer,
    indct42h integer,
    indct53h integer,
    occct31h integer,
    occct42h integer,
    occct53h integer,
    coccp31h integer,
    coccp42h integer,
    coccp53h integer,
    hour31h integer,
    hour42h integer,
    hour53h integer,
    jborg31h integer,
    jborg42h integer,
    jborg53h integer,
    union31h integer,
    union42h integer,
    union53h integer,
    bsnty31h integer,
    bsnty42h integer,
    bsnty53h integer,
    hrwg31h numeric(10,3),
    hrwg42h numeric(10,3),
    hrwg53h numeric(10,3),
    cmjhld31 integer,
    cmjhld42 integer,
    cmjhld53 integer,
    offer31h integer,
    offer42h integer,
    offer53h integer,
    ofemp31h integer,
    ofemp42h integer,
    ofemp53h integer,
    pyvac31h integer,
    pyvac42h integer,
    pyvac53h integer,
    scpay31h integer,
    scpay42h integer,
    scpay53h integer,
    paydr31h integer,
    paydr42h integer,
    paydr53h integer,
    rtpln31h integer,
    rtpln42h integer,
    rtpln53h integer
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "MIS500"."H131"
    OWNER to postgres;
